var tableauQuestion = [
    {   question : "Ce intelegi prin termenul RolePlay",
        propositionA : "Sa simulezi cat mai mult viata reala",
        propositionB : "Sa imi iau o arma si sa trag in toti",
        propositionC : "Sa imi iau o masina si sa ma plimb",
	    propositionD : "20:00-08:00",
        reponse : "A"},
		
    {   question : "In ce interval orar ai voie sa jefuiesti?",
        propositionA : "Oricand",
        propositionB : "17:00-22:00",
        propositionC : "19:00-03:00-A",
        propositionD : "20:00-08:00",
        reponse : "C"},
		
    {   question : "Ce este Meta Gamingul?",
        propositionA : "Atunci cand fug de politie",
        propositionB : "Folosirea informatiilor OOC intr-o situatie IC ( raspuns corect )",
        propositionC : "Cand injur pe cineva pe joc",
        propositionD : "Cand cineva ma ameninta cu o arma iar eu ii dau un pumn",
        reponse : "B"},
	
	{   question : "Daca o ambulanta vine cu sirenele pornite, ce trebuie sa faci ?",
        propositionA : "Sa bag viteza",
        propositionB : "Sa ma opresc si sa o filmez",
        propositionC : "Sa trag pe dreapta sa ii dau voie sa treaca(A)",
        propositionD : "Sa stau pe telefon",
        reponse : "C"},
		
	{   question : "Ce trebuie sa faci prima oara cand intri pe server?",
        propositionA : "Sa imi fac buletinul si sa merg sa muncesc. ( raspuns corect )",
        propositionB : "Sa plec de la spawn si sa fac pe mafiotul.",
        propositionC : "Sa merg cu prietenii mei sa jefuim.",
        propositionD : "Sa ma bat cu politia.",
        reponse : "A"},
		
	{   question : "Ce este Revenge Kill?",
        propositionA : "Atunci cand cineva ma omoara si eu ma razbun pe el a doua zi.",
        propositionB : "Atunci cand cineva ma omoara ma intorc si il omor si eu. ( raspuns corect )",
        propositionC : "Atunci cand cineva ma omoara si imi chem prietenii sa il rezolvam.",
        propositionD : "Atunci cand cineva imi omoara prietenul si eu merg sa il caut in oras.",
        reponse : "B"},
	
	{   question : "Cum intri intr-o mafie?",
        propositionA : "Fac aplicatie pe discord.",
        propositionB : "Vorbesc cu liderul pe chat ooc.",
        propositionC : "Caut mafioti IC si muncesc pentru ei. ( raspuns corect )",
        propositionD : "Vorbesc cu ownerul.",
        reponse : "C"},
		
	{   question : "Condusul fara permis cu ce se pedepseste ?",
        propositionA : "Avertizare(F)",
        propositionB : "Inchisoare(A)",
        propositionC : "Aruncare la gunoi(F)",
        propositionD : "Amenda de 500.000$(F)",
        reponse : "B"},
		
	{   question : "Ce inseamna OOC?",
        propositionA : "Atunci cand injur un jucator.",
        propositionB : "Informatiile din joc.",
        propositionC : "Atunci cand injur un admin.",
        propositionD : "Informatiile din Viata Reala ( discord, skype ). (raspuns corect)",
        reponse : "A"},
		
	{   question : "Puteti schimba pozitia autovehiculului, daca acesta a fost implicat intr-un accident din care a rezultat moartea sau vatamarea integritatii corporale ori a sanatatii unor persoane?",
        propositionA : "da, cu incuviintarea politiei, care cerceteaza accidentul(A)",
        propositionB : "da, daca persoana vatamata se poate deplasa singura(F)",
        propositionC : "nu, pana la sosirea ambulantei(F)",
        propositionD : "nu, pana nu fac o poza pentru facebook(F)",
        reponse : "A"},
]
